
spring.application.name=row-manage-api
api.security.token=G7n2dPpQbJq1/8yH9Lbg3jK1Yk8m2FQwzTL4b2GZqH4=
logging.level.org.springframework.security=DEBUG

spring.datasource.url=jdbc:postgresql://dpg-d71i8undiees73f3ip50-a.oregon-postgres.render.com/web_forge_manage_api_pmsb_postgres
spring.datasource.username=web_forge_manage_api_pmsb_postgres_user
spring.datasource.password=LPNjiYzAVAXqmyBayKEzdluFVu5I12NV
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


